### PR TITLE
feat: bump to monolog 3

### PR DESCRIPTION
**Pull request by SiMoSiMo2**
update dependencies
update code
update test

### CODE REVIEW

**Comment by SiMoSiMo2** [comment]
@JendaTovarys check out this PR: I've updated the code to use it with monolog 3

**Comment by SiMoSiMo2** [comment]
> @SiMoSiMo2 Thanks a lot for the PR, Simone! What's the status with the backwards compatibility with Monolog 2, do you know if that will work fine if we merge this PR? Thanks!

I think it is not compatible with Monolog 2.
There are "few" but significant changes like: 
- **log level** is now an Enum and not a constant;
- the `format()` and `formatRecord()` methods of the `JsonFormatter` class now accept a `LogRecord` object and no longer an array.

**Comment by SiMoSiMo2** [comment]
> Thanks, in that case we need to figure out a way of supporting both versions moving forward. I'll let you know once we figure something out!

Maybe two separate branches? Otherwise a hard refactoring is needed

**Comment by bsramin** [comment]
multibranch (and the master/main is the latest version) + version tag. On composer-packages there are multiple versions and the developer point to the specific version that satisfy the requirements.

Like this (https://github.com/Seldaek/monolog)

screenshot-20230119-10 30-Uuc06DOe

screenshot-20230119-10 31-r5sgHA2K

**Comment by adwhp** [comment]
@gyfis are there any updates on this PR? Monolog 3 is a requirement of Laravel 10 which was released yesterday.

**Comment by curusarn** [comment]
Hi @adwhp,

We are tracking this and we have it in our plans.
I'll be sure to keep you posted whenever I have a specific timeline to share.

**Comment by mdeboer** [comment]
Monolog 3 has been out for a year. Here's an idea, just release a new major version of this package with support only for Monolog 3 and keep the current (Monolog v2) version in a separate branch just for bugfixes. This way existing users which are stuck on 2 can still use the package and don't need to do anything. Those of us which use 3 can simply use the newest version of this package.

**Comment by curusarn** [comment]
Hi everyone,

I have created  [2.x branch](https://github.com/logtail/monolog-logtail/tree/2.x) for Monolog v2. The `master` branch will only support Monolog v3 from now on. I have released `v3.0.0` and `v2.0.0` package versions for Monolog v3 and v2, respectively. 
I have tested `v3.0.0` with Laravel 10.

Thanks, @SiMoSiMo2, for the PR and everyone else for your suggestions. 🙏

**Comment by mdeboer** [comment]
Thank you so much, will let you know if we encounter any issues 🥳

**Pull request merged**
